# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-20 21:19
from __future__ import unicode_literals

import article.models
import ckeditor_uploader.fields
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250, verbose_name='Название статьи')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Короткое описание RU')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=article.models.make_upload_path, verbose_name='Шапка статьи')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Урл')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Полное описание RU')),
            ],
            options={
                'db_table': 'article',
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
