# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-20 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_title_small',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Название статьи малое'),
        ),
    ]
