# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_article_title_small'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
